[tool.poetry]
name = "gn2gn_client"
packages = [
    { include = "import_gn" },
    { include = "geonature" },
]
version = "0.0.1"
description = "Outil d'import de données entre instances GeoNature (côté client)"
authors = ["lpofredc <frederic.cloitre@lpo.fr>"]
license = "AGPL-3.0-or-later"
classifiers= [
        "Development Status :: 1 - Planning",
        "Environment :: Console",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: French",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: Implementation :: PyPy",
        "Topic :: Documentation",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: System :: Installation/Setup",
        "Topic :: System :: Software Distribution",
    ]

[tool.poetry.scripts]
gn2gn_cli = "import_gn.transfer_gn:run"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.1"
SQLAlchemy = "^1.3.22"
psycopg2-binary = "^2.8.6"
coloredlogs = "^15.0"
schema = "^0.7.3"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
black = "^20.8b1"
flake8 = "^3.8.4"
Sphinx = "^3.4.0"
pydata-sphinx-theme = "^0.4.1"
coverage = "^5.3.1"
pylint = "^2.6.0"
mypy = "^0.790"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
